# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Deploy to Server # rsync推送文件
      uses: AEnterprise/rsync-deploy@v1.0 # 使用包装好的步骤镜像
      env:
        DEPLOY_KEY: ${{ secrets.ID_RSA }} # 引用配置，SSH私钥
        ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
        SERVER_PORT: '22' # SSH端口
        FOLDER: ./build/libs/* # 要推送的文件夹，路径相对于代码仓库的根目录
        SERVER_IP: ${{ secrets.SSH_HOST }} # 引用配置
        USERNAME: ${{ secrets.SSH_USERNAME }} # 引用配置，服务器登录名
        SERVER_DESTINATION: /home/ubuntu/libs/ # 部署到目标文件夹
    - name: ssh server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }} 
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.ID_RSA }}
    - name: Restart server
      run: |
        cd /home/ubuntu/libs
        ./mybash.sh
